# Use a fixed version as latest tag doesn't exist
# https://hub.docker.com/r/docker/compose/tags
# image:
#   name: docker:latest
#   entrypoint: ["sh", "-c"]

# services:
#   - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DEV_ENV_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/env/test-env:latest
  DOCKER_DRIVER: overlay2

build-webapp:
  stage: build
  image: docker/compose:latest
  services:
    - docker:dind
  # before_script:
  #   - apk add py-pip python-dev libffi-dev openssl-dev gcc libc-dev make && pip install docker-compose
  script:
    - echo 'build webapp'
    - docker-compose build
  only:
    # - sprint2
    - master

build-test-env:
  stage: build
  image: docker
  before_script:
    - echo $CI_DEPLOY_PASSWORD | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
    # - apk add py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  services:
      - docker:dind
  script:
      - docker pull $DOCKER_DEV_ENV_IMAGE || true
      - docker build --cache-from $DOCKER_DEV_ENV_IMAGE -t $DOCKER_DEV_ENV_IMAGE tests/
      - docker push $DOCKER_DEV_ENV_IMAGE
  only:
    # - sprint2
    - master

    
test-db:
  stage: test
  image: $DOCKER_DEV_ENV_IMAGE
  script:
    - echo 'test db'
    - python3 -m unittest discover tests.db -v
  only:
    - sprint2
    - master


test-parser:
  stage: test
  image: $DOCKER_DEV_ENV_IMAGE
  script:
    - echo 'test parser'
    - python3 -m unittest discover tests.parser -v
  only:
    # - sprint2
    - master


test-api-wolfram:
  stage: test
  image: $DOCKER_DEV_ENV_IMAGE
  script:
    - echo 'test api wolfram'
    - python3 -m unittest discover tests.api_wolfram -v
  only:
    # - sprint2
    - master


test-services:
  stage: test
  image: $DOCKER_DEV_ENV_IMAGE
  script:
    - echo 'test services'
    - python3 -m unittest discover tests.services -v
  only:
    # - sprint2
    - master


deploy-prod:
  stage: deploy
  image: ruby:latest
  before_script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl
  script:
      - dpl --provider=heroku --app=sciq-unimib --api-key=$HEROKU_SECRET_KEY
  only:
    - master

deploy-dev:
  stage: deploy
  image: ruby:latest
  before_script:
      - apt-get update -qy
      - apt-get install -y ruby-dev
      - gem install dpl
  script:
      - dpl --provider=heroku --app=sciq-unimib-dev --api-key=$HEROKU_SECRET_KEY
  only:
      - sprint2
      - master