# Use a fixed version as latest tag doesn't exist
# https://hub.docker.com/r/docker/compose/tags
image:
  name: docker/compose:1.24.1
  entrypoint: ["sh", "-c"]

services:
  - docker:dind

stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2


build-db:
  stage: build
  services:
      - docker:dind
  script:
      - echo 'build db'
      - docker-compose up -d --build web

test-db:
  stage: test
  script:
    - echo 'test db'
    - docker exec web python -m unittest discover tests.db
    - touch success
  after_script:
    - if [ ! -e success ]; then
        docker-compose logs;
      fi

    
