# Use a fixed version as latest tag doesn't exist
# https://hub.docker.com/r/docker/compose/tags
image:
  name: docker:stable
  entrypoint: ["sh", "-c"]

services:
  - docker:dind

before_script:
  - apk add --update python py-pip python-dev git openssh-client && pip install docker-compose
    

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

test:
  stage: test
  before_script:
    - docker version
    - docker-compose version
  script:
    - echo 'test'
    - ./test.sh
    - touch success
  after_script:
    - if [ ! -e success ]; then
        docker-compose logs;
      fi
    
