# Use a fixed version as latest tag doesn't exist
# https://hub.docker.com/r/docker/compose/tags
image:
  name: docker/compose:1.24.1
  entrypoint: ["sh", "-c"]

services:
  - docker:dind

stages:
  - test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2


build-db:
  stage: build
  services:
      - docker:dind
  script:
      - echo 'build db'
      - docker-compose up -d --build web

test-db:
  stage: test
  script:
    - echo 'test db'
    - python -m unittest discover tests.db -v

test-parser:
  stage: test
  before-script:
    - apt-get -qq install -y python python-pip
    - pip install -r ./web/requirements.txt
  script:
    - echo 'test parser'
    - python -m unittest discover tests.parser -v
    
