# Use a fixed version as latest tag doesn't exist
# https://hub.docker.com/r/docker/compose/tags
image:
  name: alpine:latest
  entrypoint: ["sh", "-c"]

services:
  - docker:dind

stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2


#build-db:
#  stage: build
#  services:
#      - docker:dind
#  script:
#      - echo 'build db'
#      - docker-compose up -d --build web

test-db:
  stage: test
  before_script:
    - apk update
    - apk add python3
    - apk add py3-pip
    - pip3 install -r ./web/requirements.txt
  script:
    - echo 'test db'
    - python3 -m unittest discover tests.db -v

test-parser:
  stage: test
  before_script:
    - apk update
    - apk add python3
    - apk add py3-pip
  script:
    - echo 'test parser'
    - python3 -m unittest discover tests.parser -v
    
