version: "3.3"
services:
  web:
    container_name: 'web'
    build: 
      context: .
      args: 
        MIGRATE: ${MIGRATE}
    image: web
    links: 
      - db
    ports:
      - "5000:5000"
    env_file: 
      - .env
    restart: 
      always
    networks: 
      - backend
    volumes:
      # volume for store plot 
      - type: volume
        source: plot-expression
        target: /usr/src/siq/app/api/plot
      # volume for mapping host folder to container 
      - type: bind
        source: ./migrations
        target: /usr/src/sciq/migrations
      #- type: volume
      #  source: migrations-data
      #  target: /usr/src/sciq/migrations
      

  db:
    container_name: 'db'
    image: mysql:5.7
    ports:
      - "3306:3306"  
    command: "--innodb_use_native_aio=0" 
    environment:
      MYSQL_DATABASE: sciq
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    restart: 
      always
    networks: 
      - backend
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql

networks:
  backend:

volumes: 
  mysql-data:
    driver: 
      local
  plot-expression:
    driver:
      local
  # migrations-data:
  #  driver: 
  #    local