version: "3.3"
services:
  web:
    container_name: 'web'
    build: .
    links: 
      - db
    ports:
      - "5000:5000"
    env_file: 
      - .env
    restart: 
      always
    networks: 
      - backend
    volumes:
      - type: volume
        source: plot-expression
        target: /user/src/siq/app/api/plot

  db:
    container_name: 'db'
    image: mysql:5.7
    ports:
      - "3306:3306"  
    command: "--innodb_use_native_aio=0" 
    environment:
      MYSQL_DATABASE: sciq
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    restart: 
      always
    networks: 
      - backend
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql

networks:
  backend:

volumes: 
  mysql-data:
    driver: 
      local
  plot-expression:
    driver:
      local