version: "3.3"
services:
  web:
    container_name: 'web'
    build: .
    links: 
      - db
    ports:
      - "5000:5000"
    env_file: 
      - .env
    restart: 
      always
    networks: 
      - backend
    volumes:
      - type: bind
        source: ./migrations
        target: /usr/src/sciq/migrations

  db:
    container_name: 'db'
    image: mysql:5.7
    ports:
      - "32000:3306"  
    command: "--innodb_use_native_aio=0" 
    environment:
      MYSQL_DATABASE: sciq
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    restart: 
      always
    networks: 
      - backend
    volumes:
      - type: bind
        source: ./mysql-data
        target: /var/lib/mysql

networks:
  backend: