version: "3.3"
services:
  web:
    container_name: 'web'
    build: 
      context: $PWD
      dockerfile: $PWD/web/Dockerfile
    image: web
    links: 
      - db
      - mongodb
    ports:
      - "5000:5000"

    env_file: 
      - ./web/.env
    restart: 
      always
    networks: 
      - backend
    volumes:
      # volume for mapping host migrations folder to container 
      - type: bind
        source: ./web/migrations
        target: /usr/src/sciq/web/migrations

  db:
    container_name: 'db'
    image: mysql:5.7
    ports:
      - "3306:3306"  
    environment:
      MYSQL_DATABASE: sciq
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    restart: 
      always
    networks: 
      - backend
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
 


  mongodb:
    image: mongo:4.0.8
    ports:
      - "27017:27017"
    container_name: mongodb
    restart: always
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_mongo
      MONGO_INITDB_ROOT_PASSWORD: root_mongo
      MONGO_INITDB_DATABASE: sciq_mongo
    networks:
      - backend
    volumes:
      - type: volume
        source: mongodb-data
        target: /data/db

 
networks:
  backend:

volumes: 
  mysql-data:
    driver: 
      local
  mongodb-data:
    driver:
      local



