"""add execution_time

Revision ID: 0e995ac80b72
Revises: d3d9358db27e
Create Date: 2020-03-27 11:01:49.735304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e995ac80b72'
down_revision = 'd3d9358db27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expression', sa.Column('execution_time', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expression', 'execution_time')
    # ### end Alembic commands ###
