"""delete ex_type and length

Revision ID: 515dc72c00bc
Revises: 0e995ac80b72
Create Date: 2020-03-27 23:15:23.971800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '515dc72c00bc'
down_revision = '0e995ac80b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expression', 'expression',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.drop_index('ix_expression_expression_type', table_name='expression')
    op.drop_column('expression', 'expression_type')
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.add_column('expression', sa.Column('expression_type', mysql.VARCHAR(length=128), nullable=True))
    op.create_index('ix_expression_expression_type', 'expression', ['expression_type'], unique=False)
    op.alter_column('expression', 'expression',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
