"""empty message

Revision ID: 87a16ed70936
Revises: 51504aa56346
Create Date: 2020-03-29 19:50:21.029976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87a16ed70936'
down_revision = '51504aa56346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expression_expression_type', table_name='expression')
    op.drop_column('expression', 'expression_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expression', sa.Column('expression_type', mysql.VARCHAR(length=128), nullable=True))
    op.create_index('ix_expression_expression_type', 'expression', ['expression_type'], unique=False)
    # ### end Alembic commands ###
