"""prova

Revision ID: c1dbc8f70b71
Revises: 
Create Date: 2020-03-27 10:44:12.518112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1dbc8f70b71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('expression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expression', sa.String(length=64), nullable=False),
    sa.Column('expression_type', sa.String(length=128), nullable=True),
    sa.Column('solutions', sa.String(length=128), nullable=True),
    sa.Column('step', sa.String(length=128), nullable=True),
    sa.Column('plot', sa.String(length=128), nullable=True),
    sa.Column('alternate_forms', sa.String(length=128), nullable=True),
    sa.Column('execution_time', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'expression', name='_user_expression_uc')
    )
    op.create_index(op.f('ix_expression_expression'), 'expression', ['expression'], unique=False)
    op.create_index(op.f('ix_expression_expression_type'), 'expression', ['expression_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expression_expression_type'), table_name='expression')
    op.drop_index(op.f('ix_expression_expression'), table_name='expression')
    op.drop_table('expression')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
