"""delete expression_time

Revision ID: d3d9358db27e
Revises: c1dbc8f70b71
Create Date: 2020-03-27 10:52:16.056123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3d9358db27e'
down_revision = 'c1dbc8f70b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expression', 'execution_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expression', sa.Column('execution_time', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
