"""delete step

Revision ID: f7055f3e8c02
Revises: 515dc72c00bc
Create Date: 2020-03-27 23:45:41.458672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7055f3e8c02'
down_revision = '515dc72c00bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expression', 'step')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expression', sa.Column('step', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
