"""empty message

Revision ID: 081065896071
Revises: 50ffce28d70e
Create Date: 2020-04-24 09:28:00.375524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '081065896071'
down_revision = '50ffce28d70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expression_expression', table_name='expression')
    op.drop_table('expression')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expression',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('expression', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('solutions', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('alternate_forms', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('execution_time', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('integral', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('limits', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('partial_derivates', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('plots', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('results', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('symbolic_solutions', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_expression_expression', 'expression', ['expression'], unique=False)
    # ### end Alembic commands ###
