"""empty message

Revision ID: 1c7fd9c2ff9b
Revises: 081065896071
Create Date: 2020-05-26 13:52:31.942252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c7fd9c2ff9b'
down_revision = '081065896071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WARNING')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WARNING',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('warning', mysql.TEXT(), nullable=True),
    sa.Column('Bitcoin_Address', mysql.TEXT(), nullable=True),
    sa.Column('Email', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
