"""empty message

Revision ID: 2b277b4bb278
Revises: 081065896071
Create Date: 2020-05-07 15:35:47.290546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b277b4bb278'
down_revision = '081065896071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appid', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('username_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['username_fk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_appid'), 'application', ['appid'], unique=True)
    op.create_index(op.f('ix_application_name'), 'application', ['name'], unique=False)
    op.create_index(op.f('ix_application_username'), 'application', ['username_fk'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_username'), table_name='application')
    op.drop_index(op.f('ix_application_name'), table_name='application')
    op.drop_index(op.f('ix_application_appid'), table_name='application')
    op.drop_table('application')
    # ### end Alembic commands ###
