"""empty message

Revision ID: 4c9258980970
Revises: 1ba64e7245a2
Create Date: 2020-03-30 15:45:22.303419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9258980970'
down_revision = '1ba64e7245a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expression_expression', table_name='expression')
    op.create_index(op.f('ix_expression_expression'), 'expression', ['expression'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expression_expression'), table_name='expression')
    op.create_index('ix_expression_expression', 'expression', ['expression'], unique=False)
    # ### end Alembic commands ###
