"""empty message

Revision ID: b1d9ab51fec2
Revises: eabd080b1282
Create Date: 2020-03-30 16:21:23.191113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d9ab51fec2'
down_revision = 'eabd080b1282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_expression', ['user_id', 'expression_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_expression', type_='unique')
    # ### end Alembic commands ###
