"""empty message

Revision ID: eabd080b1282
Revises: 4c9258980970
Create Date: 2020-03-30 16:09:54.172997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabd080b1282'
down_revision = '4c9258980970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expression_expression', table_name='expression')
    op.create_index(op.f('ix_expression_expression'), 'expression', ['expression'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expression_expression'), table_name='expression')
    op.create_index('ix_expression_expression', 'expression', ['expression'], unique=True)
    # ### end Alembic commands ###
